# NOTE: update this with your service name
service: content-life-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    eventTable: calendar-test-db
    ideaTable: idea-test-db
    storyTable: storyboard-test-db
    boardTable: board-test-db
    tokenStore: tokenStore-test-db
    googleTokenStore: googleTokenStore-test-db

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:us-east-1:*:*'

functions:
  createEvent:
    handler: apps/calendar/routes/create.main
    events:
      - http:
          path: events
          method: post
          cors: true
          authorizer: aws_iam
  getEvent:
    handler: apps/calendar/routes/get.main
    events:
      - http:
          path: events/{id}
          method: get
          cors: true
          authorizer: aws_iam
  listEvents:
    handler: apps/calendar/routes/list.main
    events:
      - http:
          path: events
          method: get
          cors: true
          authorizer: aws_iam
  updateEvent:
    handler: apps/calendar/routes/update.main
    events:
      - http:
          path: events/{id}
          method: put
          cors: true
          authorizer: aws_iam
  deleteEvent:
    handler: apps/calendar/routes/delete.main
    events:
      - http:
          path: events/{id}
          method: delete
          cors: true
          authorizer: aws_iam
  createIdea:
    handler: apps/ideas/routes/create.main
    events:
      - http:
          path: ideas
          method: post
          cors: true
          authorizer: aws_iam
  getIdea:
    handler: apps/ideas/routes/get.main
    events:
      - http:
          path: ideas/{id}
          method: get
          cors: true
          authorizer: aws_iam
  listIdeas:
    handler: apps/ideas/routes/list.main
    events:
      - http:
          path: ideas
          method: get
          cors: true
          authorizer: aws_iam
  updateIdea:
    handler: apps/ideas/routes/update.main
    events:
      - http:
          path: ideas/{id}
          method: put
          cors: true
          authorizer: aws_iam
  deleteIdea:
    handler: apps/ideas/routes/delete.main
    events:
      - http:
          path: ideas/{id}
          method: delete
          cors: true
          authorizer: aws_iam
  createStory:
    handler: apps/storyboard/routes/createStories.main
    events:
      - http:
          path: stories
          method: post
          cors: true
          authorizer: aws_iam
  createBoard:
    handler: apps/storyboard/routes/createBoard.main
    events:
      - http:
          path: boards
          method: post
          cors: true
          authorizer: aws_iam
  listStories:
    handler: apps/storyboard/routes/listStories.main
    events:
      - http:
          path: stories
          method: get
          cors: true
          authorizer: aws_iam
  listBoards:
    handler: apps/storyboard/routes/listBoards.main
    events:
      - http:
          path: boards/{id}
          method: get
          cors: true
          authorizer: aws_iam
  updateStory:
    handler: apps/storyboard/routes/updateStory.main
    events:
      - http:
          path: stories/{id}
          method: put
          cors: true
          authorizer: aws_iam
  updateBoard:
    handler: apps/storyboard/routes/updateBoard.main
    events:
      - http:
          path: board/{id}
          method: put
          cors: true
          authorizer: aws_iam
  deleteStory:
    handler: apps/storyboard/routes/deleteStory.main
    events:
      - http:
          path: story/{id}
          method: delete
          cors: true
          authorizer: aws_iam
  deleteBoard:
    handler: apps/storyboard/routes/deleteBoard.main
    events:
      - http:
          path: board/{id}
          method: delete
          cors: true
          authorizer: aws_iam
  createFacebookToken:
    handler: apps/tokens/facebook/createToken.main
    events:
      - http:
          path: fbtoken
          method: post
          cors: true
          authorizer: aws_iam
  createGoogleToken:
    handler: apps/tokens/youtube/createToken.main
    events:
      - http:
          path: googletoken
          method: post
          cors: true
          authorizer: aws_iam
  getFacebookToken:
    handler: apps/tokens/facebook/getToken.main
    events:
      - http:
          path: fbtoken
          method: get
          cors: true
          authorizer: aws_iam
  getGoogleToken:
    handler: apps/tokens/youtube/getToken.main
    events:
      - http:
          path: googletoken
          method: get
          cors: true
          authorizer: aws_iam
